// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driving_data.proto

#include "driving_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace pbt {
PROTOBUF_CONSTEXPR Vec3::Vec3(
    ::_pbi::ConstantInitialized)
  : x_(0)
  , y_(0)
  , z_(0){}
struct Vec3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vec3DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vec3DefaultTypeInternal() {}
  union {
    Vec3 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vec3DefaultTypeInternal _Vec3_default_instance_;
PROTOBUF_CONSTEXPR Ego::Ego(
    ::_pbi::ConstantInitialized)
  : obstacles_()
  , vehicle_(nullptr){}
struct EgoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EgoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EgoDefaultTypeInternal() {}
  union {
    Ego _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EgoDefaultTypeInternal _Ego_default_instance_;
PROTOBUF_CONSTEXPR EgoVehicle::EgoVehicle(
    ::_pbi::ConstantInitialized)
  : position_(nullptr)
  , velocity_(nullptr)
  , rotation_(nullptr)
  , timestamp_(int64_t{0})
  , id_(0){}
struct EgoVehicleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EgoVehicleDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EgoVehicleDefaultTypeInternal() {}
  union {
    EgoVehicle _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EgoVehicleDefaultTypeInternal _EgoVehicle_default_instance_;
PROTOBUF_CONSTEXPR Obstacle::Obstacle(
    ::_pbi::ConstantInitialized)
  : position_(nullptr)
  , velocity_(nullptr)
  , size_(nullptr)
  , id_(0)
  , type_(0)

  , heading_(0){}
struct ObstacleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ObstacleDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObstacleDefaultTypeInternal() {}
  union {
    Obstacle _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObstacleDefaultTypeInternal _Obstacle_default_instance_;
PROTOBUF_CONSTEXPR Cross::Cross(
    ::_pbi::ConstantInitialized)
  : lane_lines_()
  , ground_signs_()
  , drivable_areas_(){}
struct CrossDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CrossDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CrossDefaultTypeInternal() {}
  union {
    Cross _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CrossDefaultTypeInternal _Cross_default_instance_;
PROTOBUF_CONSTEXPR LaneLine::LaneLine(
    ::_pbi::ConstantInitialized)
  : points_()
  , id_(0)
  , type_(0)

  , confidence_(0)
  , width_(0)
  , color_(0)
{}
struct LaneLineDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LaneLineDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LaneLineDefaultTypeInternal() {}
  union {
    LaneLine _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LaneLineDefaultTypeInternal _LaneLine_default_instance_;
PROTOBUF_CONSTEXPR GroundSign::GroundSign(
    ::_pbi::ConstantInitialized)
  : polygon_()
  , id_(0)
  , type_(0)
{}
struct GroundSignDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GroundSignDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GroundSignDefaultTypeInternal() {}
  union {
    GroundSign _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GroundSignDefaultTypeInternal _GroundSign_default_instance_;
PROTOBUF_CONSTEXPR DrivableArea::DrivableArea(
    ::_pbi::ConstantInitialized)
  : boundary_()
  , confidence_(0)
  , speed_limit_(0)
  , id_(0){}
struct DrivableAreaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DrivableAreaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DrivableAreaDefaultTypeInternal() {}
  union {
    DrivableArea _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DrivableAreaDefaultTypeInternal _DrivableArea_default_instance_;
PROTOBUF_CONSTEXPR DrivingDataFrame::DrivingDataFrame(
    ::_pbi::ConstantInitialized)
  : ego_(nullptr)
  , cross_(nullptr)
  , frame_id_(int64_t{0})
  , timestamp_(int64_t{0}){}
struct DrivingDataFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DrivingDataFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DrivingDataFrameDefaultTypeInternal() {}
  union {
    DrivingDataFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DrivingDataFrameDefaultTypeInternal _DrivingDataFrame_default_instance_;
}  // namespace pbt
namespace pbt {
bool ObstacleType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> ObstacleType_strings[10] = {};

static const char ObstacleType_names[] =
  "OBSTACLE_ANIMAL"
  "OBSTACLE_BUS"
  "OBSTACLE_CONE"
  "OBSTACLE_CYCLIST"
  "OBSTACLE_GUARDRAIL"
  "OBSTACLE_MOTORCYCLE"
  "OBSTACLE_PEDESTRIAN"
  "OBSTACLE_TRUCK"
  "OBSTACLE_UNKNOWN"
  "OBSTACLE_VEHICLE";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry ObstacleType_entries[] = {
  { {ObstacleType_names + 0, 15}, 7 },
  { {ObstacleType_names + 15, 12}, 5 },
  { {ObstacleType_names + 27, 13}, 8 },
  { {ObstacleType_names + 40, 16}, 3 },
  { {ObstacleType_names + 56, 18}, 9 },
  { {ObstacleType_names + 74, 19}, 6 },
  { {ObstacleType_names + 93, 19}, 2 },
  { {ObstacleType_names + 112, 14}, 4 },
  { {ObstacleType_names + 126, 16}, 0 },
  { {ObstacleType_names + 142, 16}, 1 },
};

static const int ObstacleType_entries_by_number[] = {
  8, // 0 -> OBSTACLE_UNKNOWN
  9, // 1 -> OBSTACLE_VEHICLE
  6, // 2 -> OBSTACLE_PEDESTRIAN
  3, // 3 -> OBSTACLE_CYCLIST
  7, // 4 -> OBSTACLE_TRUCK
  1, // 5 -> OBSTACLE_BUS
  5, // 6 -> OBSTACLE_MOTORCYCLE
  0, // 7 -> OBSTACLE_ANIMAL
  2, // 8 -> OBSTACLE_CONE
  4, // 9 -> OBSTACLE_GUARDRAIL
};

const std::string& ObstacleType_Name(
    ObstacleType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          ObstacleType_entries,
          ObstacleType_entries_by_number,
          10, ObstacleType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      ObstacleType_entries,
      ObstacleType_entries_by_number,
      10, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     ObstacleType_strings[idx].get();
}
bool ObstacleType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ObstacleType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      ObstacleType_entries, 10, name, &int_value);
  if (success) {
    *value = static_cast<ObstacleType>(int_value);
  }
  return success;
}
bool LaneLineType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> LaneLineType_strings[8] = {};

static const char LaneLineType_names[] =
  "LANE_CURB"
  "LANE_DASHED"
  "LANE_DOUBLE_DASHED"
  "LANE_DOUBLE_SOLID"
  "LANE_ROAD_EDGE"
  "LANE_SOLID"
  "LANE_SOLID_DASHED"
  "LANE_UNKNOWN";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry LaneLineType_entries[] = {
  { {LaneLineType_names + 0, 9}, 6 },
  { {LaneLineType_names + 9, 11}, 2 },
  { {LaneLineType_names + 20, 18}, 4 },
  { {LaneLineType_names + 38, 17}, 3 },
  { {LaneLineType_names + 55, 14}, 7 },
  { {LaneLineType_names + 69, 10}, 1 },
  { {LaneLineType_names + 79, 17}, 5 },
  { {LaneLineType_names + 96, 12}, 0 },
};

static const int LaneLineType_entries_by_number[] = {
  7, // 0 -> LANE_UNKNOWN
  5, // 1 -> LANE_SOLID
  1, // 2 -> LANE_DASHED
  3, // 3 -> LANE_DOUBLE_SOLID
  2, // 4 -> LANE_DOUBLE_DASHED
  6, // 5 -> LANE_SOLID_DASHED
  0, // 6 -> LANE_CURB
  4, // 7 -> LANE_ROAD_EDGE
};

const std::string& LaneLineType_Name(
    LaneLineType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          LaneLineType_entries,
          LaneLineType_entries_by_number,
          8, LaneLineType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      LaneLineType_entries,
      LaneLineType_entries_by_number,
      8, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     LaneLineType_strings[idx].get();
}
bool LaneLineType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LaneLineType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      LaneLineType_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<LaneLineType>(int_value);
  }
  return success;
}
bool LaneLineColor_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> LaneLineColor_strings[5] = {};

static const char LaneLineColor_names[] =
  "LANE_COLOR_BLUE"
  "LANE_COLOR_GREEN"
  "LANE_COLOR_UNKNOWN"
  "LANE_COLOR_WHITE"
  "LANE_COLOR_YELLOW";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry LaneLineColor_entries[] = {
  { {LaneLineColor_names + 0, 15}, 3 },
  { {LaneLineColor_names + 15, 16}, 4 },
  { {LaneLineColor_names + 31, 18}, 0 },
  { {LaneLineColor_names + 49, 16}, 1 },
  { {LaneLineColor_names + 65, 17}, 2 },
};

static const int LaneLineColor_entries_by_number[] = {
  2, // 0 -> LANE_COLOR_UNKNOWN
  3, // 1 -> LANE_COLOR_WHITE
  4, // 2 -> LANE_COLOR_YELLOW
  0, // 3 -> LANE_COLOR_BLUE
  1, // 4 -> LANE_COLOR_GREEN
};

const std::string& LaneLineColor_Name(
    LaneLineColor value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          LaneLineColor_entries,
          LaneLineColor_entries_by_number,
          5, LaneLineColor_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      LaneLineColor_entries,
      LaneLineColor_entries_by_number,
      5, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     LaneLineColor_strings[idx].get();
}
bool LaneLineColor_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LaneLineColor* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      LaneLineColor_entries, 5, name, &int_value);
  if (success) {
    *value = static_cast<LaneLineColor>(int_value);
  }
  return success;
}
bool GroundSignType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> GroundSignType_strings[14] = {};

static const char GroundSignType_names[] =
  "SIGN_ARROW_LEFT"
  "SIGN_ARROW_LEFT_RIGHT"
  "SIGN_ARROW_RIGHT"
  "SIGN_ARROW_STRAIGHT"
  "SIGN_ARROW_STRAIGHT_LEFT"
  "SIGN_ARROW_STRAIGHT_RIGHT"
  "SIGN_ARROW_UTURN"
  "SIGN_CROSSWALK"
  "SIGN_PARKING_SPACE"
  "SIGN_SPEED_BUMP"
  "SIGN_STOP_LINE"
  "SIGN_UNKNOWN"
  "SIGN_YIELD_LINE"
  "SIGN_ZEBRA_CROSSING";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry GroundSignType_entries[] = {
  { {GroundSignType_names + 0, 15}, 2 },
  { {GroundSignType_names + 15, 21}, 7 },
  { {GroundSignType_names + 36, 16}, 3 },
  { {GroundSignType_names + 52, 19}, 1 },
  { {GroundSignType_names + 71, 24}, 5 },
  { {GroundSignType_names + 95, 25}, 6 },
  { {GroundSignType_names + 120, 16}, 4 },
  { {GroundSignType_names + 136, 14}, 8 },
  { {GroundSignType_names + 150, 18}, 12 },
  { {GroundSignType_names + 168, 15}, 10 },
  { {GroundSignType_names + 183, 14}, 9 },
  { {GroundSignType_names + 197, 12}, 0 },
  { {GroundSignType_names + 209, 15}, 11 },
  { {GroundSignType_names + 224, 19}, 13 },
};

static const int GroundSignType_entries_by_number[] = {
  11, // 0 -> SIGN_UNKNOWN
  3, // 1 -> SIGN_ARROW_STRAIGHT
  0, // 2 -> SIGN_ARROW_LEFT
  2, // 3 -> SIGN_ARROW_RIGHT
  6, // 4 -> SIGN_ARROW_UTURN
  4, // 5 -> SIGN_ARROW_STRAIGHT_LEFT
  5, // 6 -> SIGN_ARROW_STRAIGHT_RIGHT
  1, // 7 -> SIGN_ARROW_LEFT_RIGHT
  7, // 8 -> SIGN_CROSSWALK
  10, // 9 -> SIGN_STOP_LINE
  9, // 10 -> SIGN_SPEED_BUMP
  12, // 11 -> SIGN_YIELD_LINE
  8, // 12 -> SIGN_PARKING_SPACE
  13, // 13 -> SIGN_ZEBRA_CROSSING
};

const std::string& GroundSignType_Name(
    GroundSignType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          GroundSignType_entries,
          GroundSignType_entries_by_number,
          14, GroundSignType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      GroundSignType_entries,
      GroundSignType_entries_by_number,
      14, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     GroundSignType_strings[idx].get();
}
bool GroundSignType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GroundSignType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      GroundSignType_entries, 14, name, &int_value);
  if (success) {
    *value = static_cast<GroundSignType>(int_value);
  }
  return success;
}

// ===================================================================

class Vec3::_Internal {
 public:
};

Vec3::Vec3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.Vec3)
}
Vec3::Vec3(const Vec3& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:pbt.Vec3)
}

inline void Vec3::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&x_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

Vec3::~Vec3() {
  // @@protoc_insertion_point(destructor:pbt.Vec3)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Vec3::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Vec3::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Vec3::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.Vec3)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
  _internal_metadata_.Clear<std::string>();
}

const char* Vec3::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Vec3::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.Vec3)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_x(), target);
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_y(), target);
  }

  // double z = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = this->_internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.Vec3)
  return target;
}

size_t Vec3::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.Vec3)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 8;
  }

  // double z = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = this->_internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Vec3::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Vec3*>(
      &from));
}

void Vec3::MergeFrom(const Vec3& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.Vec3)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = from._internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = from._internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_z = from._internal_z();
  uint64_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _internal_set_z(from._internal_z());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Vec3::CopyFrom(const Vec3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.Vec3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vec3::IsInitialized() const {
  return true;
}

void Vec3::InternalSwap(Vec3* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vec3, z_)
      + sizeof(Vec3::z_)
      - PROTOBUF_FIELD_OFFSET(Vec3, x_)>(
          reinterpret_cast<char*>(&x_),
          reinterpret_cast<char*>(&other->x_));
}

std::string Vec3::GetTypeName() const {
  return "pbt.Vec3";
}


// ===================================================================

class Ego::_Internal {
 public:
  static const ::pbt::EgoVehicle& vehicle(const Ego* msg);
};

const ::pbt::EgoVehicle&
Ego::_Internal::vehicle(const Ego* msg) {
  return *msg->vehicle_;
}
Ego::Ego(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  obstacles_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.Ego)
}
Ego::Ego(const Ego& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      obstacles_(from.obstacles_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_vehicle()) {
    vehicle_ = new ::pbt::EgoVehicle(*from.vehicle_);
  } else {
    vehicle_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:pbt.Ego)
}

inline void Ego::SharedCtor() {
vehicle_ = nullptr;
}

Ego::~Ego() {
  // @@protoc_insertion_point(destructor:pbt.Ego)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Ego::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete vehicle_;
}

void Ego::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Ego::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.Ego)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  obstacles_.Clear();
  if (GetArenaForAllocation() == nullptr && vehicle_ != nullptr) {
    delete vehicle_;
  }
  vehicle_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* Ego::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .pbt.EgoVehicle vehicle = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_vehicle(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .pbt.Obstacle obstacles = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_obstacles(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ego::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.Ego)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .pbt.EgoVehicle vehicle = 1;
  if (this->_internal_has_vehicle()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::vehicle(this),
        _Internal::vehicle(this).GetCachedSize(), target, stream);
  }

  // repeated .pbt.Obstacle obstacles = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_obstacles_size()); i < n; i++) {
    const auto& repfield = this->_internal_obstacles(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.Ego)
  return target;
}

size_t Ego::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.Ego)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pbt.Obstacle obstacles = 2;
  total_size += 1UL * this->_internal_obstacles_size();
  for (const auto& msg : this->obstacles_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .pbt.EgoVehicle vehicle = 1;
  if (this->_internal_has_vehicle()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *vehicle_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Ego::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Ego*>(
      &from));
}

void Ego::MergeFrom(const Ego& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.Ego)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  obstacles_.MergeFrom(from.obstacles_);
  if (from._internal_has_vehicle()) {
    _internal_mutable_vehicle()->::pbt::EgoVehicle::MergeFrom(from._internal_vehicle());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Ego::CopyFrom(const Ego& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.Ego)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ego::IsInitialized() const {
  return true;
}

void Ego::InternalSwap(Ego* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  obstacles_.InternalSwap(&other->obstacles_);
  swap(vehicle_, other->vehicle_);
}

std::string Ego::GetTypeName() const {
  return "pbt.Ego";
}


// ===================================================================

class EgoVehicle::_Internal {
 public:
  static const ::pbt::Vec3& position(const EgoVehicle* msg);
  static const ::pbt::Vec3& velocity(const EgoVehicle* msg);
  static const ::pbt::Vec3& rotation(const EgoVehicle* msg);
};

const ::pbt::Vec3&
EgoVehicle::_Internal::position(const EgoVehicle* msg) {
  return *msg->position_;
}
const ::pbt::Vec3&
EgoVehicle::_Internal::velocity(const EgoVehicle* msg) {
  return *msg->velocity_;
}
const ::pbt::Vec3&
EgoVehicle::_Internal::rotation(const EgoVehicle* msg) {
  return *msg->rotation_;
}
EgoVehicle::EgoVehicle(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.EgoVehicle)
}
EgoVehicle::EgoVehicle(const EgoVehicle& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_position()) {
    position_ = new ::pbt::Vec3(*from.position_);
  } else {
    position_ = nullptr;
  }
  if (from._internal_has_velocity()) {
    velocity_ = new ::pbt::Vec3(*from.velocity_);
  } else {
    velocity_ = nullptr;
  }
  if (from._internal_has_rotation()) {
    rotation_ = new ::pbt::Vec3(*from.rotation_);
  } else {
    rotation_ = nullptr;
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:pbt.EgoVehicle)
}

inline void EgoVehicle::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&position_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&position_)) + sizeof(id_));
}

EgoVehicle::~EgoVehicle() {
  // @@protoc_insertion_point(destructor:pbt.EgoVehicle)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EgoVehicle::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete position_;
  if (this != internal_default_instance()) delete velocity_;
  if (this != internal_default_instance()) delete rotation_;
}

void EgoVehicle::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EgoVehicle::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.EgoVehicle)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && velocity_ != nullptr) {
    delete velocity_;
  }
  velocity_ = nullptr;
  if (GetArenaForAllocation() == nullptr && rotation_ != nullptr) {
    delete rotation_;
  }
  rotation_ = nullptr;
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(id_));
  _internal_metadata_.Clear<std::string>();
}

const char* EgoVehicle::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.Vec3 position = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.Vec3 velocity = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_velocity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.Vec3 rotation = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_rotation(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EgoVehicle::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.EgoVehicle)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // .pbt.Vec3 position = 2;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .pbt.Vec3 velocity = 3;
  if (this->_internal_has_velocity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::velocity(this),
        _Internal::velocity(this).GetCachedSize(), target, stream);
  }

  // .pbt.Vec3 rotation = 5;
  if (this->_internal_has_rotation()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::rotation(this),
        _Internal::rotation(this).GetCachedSize(), target, stream);
  }

  // int64 timestamp = 10;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(10, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.EgoVehicle)
  return target;
}

size_t EgoVehicle::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.EgoVehicle)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .pbt.Vec3 position = 2;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *position_);
  }

  // .pbt.Vec3 velocity = 3;
  if (this->_internal_has_velocity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *velocity_);
  }

  // .pbt.Vec3 rotation = 5;
  if (this->_internal_has_rotation()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *rotation_);
  }

  // int64 timestamp = 10;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EgoVehicle::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const EgoVehicle*>(
      &from));
}

void EgoVehicle::MergeFrom(const EgoVehicle& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.EgoVehicle)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _internal_mutable_position()->::pbt::Vec3::MergeFrom(from._internal_position());
  }
  if (from._internal_has_velocity()) {
    _internal_mutable_velocity()->::pbt::Vec3::MergeFrom(from._internal_velocity());
  }
  if (from._internal_has_rotation()) {
    _internal_mutable_rotation()->::pbt::Vec3::MergeFrom(from._internal_rotation());
  }
  if (from._internal_timestamp() != 0) {
    _internal_set_timestamp(from._internal_timestamp());
  }
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void EgoVehicle::CopyFrom(const EgoVehicle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.EgoVehicle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoVehicle::IsInitialized() const {
  return true;
}

void EgoVehicle::InternalSwap(EgoVehicle* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EgoVehicle, id_)
      + sizeof(EgoVehicle::id_)
      - PROTOBUF_FIELD_OFFSET(EgoVehicle, position_)>(
          reinterpret_cast<char*>(&position_),
          reinterpret_cast<char*>(&other->position_));
}

std::string EgoVehicle::GetTypeName() const {
  return "pbt.EgoVehicle";
}


// ===================================================================

class Obstacle::_Internal {
 public:
  static const ::pbt::Vec3& position(const Obstacle* msg);
  static const ::pbt::Vec3& velocity(const Obstacle* msg);
  static const ::pbt::Vec3& size(const Obstacle* msg);
};

const ::pbt::Vec3&
Obstacle::_Internal::position(const Obstacle* msg) {
  return *msg->position_;
}
const ::pbt::Vec3&
Obstacle::_Internal::velocity(const Obstacle* msg) {
  return *msg->velocity_;
}
const ::pbt::Vec3&
Obstacle::_Internal::size(const Obstacle* msg) {
  return *msg->size_;
}
Obstacle::Obstacle(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.Obstacle)
}
Obstacle::Obstacle(const Obstacle& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_position()) {
    position_ = new ::pbt::Vec3(*from.position_);
  } else {
    position_ = nullptr;
  }
  if (from._internal_has_velocity()) {
    velocity_ = new ::pbt::Vec3(*from.velocity_);
  } else {
    velocity_ = nullptr;
  }
  if (from._internal_has_size()) {
    size_ = new ::pbt::Vec3(*from.size_);
  } else {
    size_ = nullptr;
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&heading_) -
    reinterpret_cast<char*>(&id_)) + sizeof(heading_));
  // @@protoc_insertion_point(copy_constructor:pbt.Obstacle)
}

inline void Obstacle::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&position_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&heading_) -
    reinterpret_cast<char*>(&position_)) + sizeof(heading_));
}

Obstacle::~Obstacle() {
  // @@protoc_insertion_point(destructor:pbt.Obstacle)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Obstacle::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete position_;
  if (this != internal_default_instance()) delete velocity_;
  if (this != internal_default_instance()) delete size_;
}

void Obstacle::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Obstacle::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.Obstacle)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && velocity_ != nullptr) {
    delete velocity_;
  }
  velocity_ = nullptr;
  if (GetArenaForAllocation() == nullptr && size_ != nullptr) {
    delete size_;
  }
  size_ = nullptr;
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&heading_) -
      reinterpret_cast<char*>(&id_)) + sizeof(heading_));
  _internal_metadata_.Clear<std::string>();
}

const char* Obstacle::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.ObstacleType type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::pbt::ObstacleType>(val));
        } else
          goto handle_unusual;
        continue;
      // .pbt.Vec3 position = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.Vec3 velocity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_velocity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.Vec3 size = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_size(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double heading = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          heading_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Obstacle::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.Obstacle)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // .pbt.ObstacleType type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  // .pbt.Vec3 position = 3;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .pbt.Vec3 velocity = 4;
  if (this->_internal_has_velocity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::velocity(this),
        _Internal::velocity(this).GetCachedSize(), target, stream);
  }

  // .pbt.Vec3 size = 6;
  if (this->_internal_has_size()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::size(this),
        _Internal::size(this).GetCachedSize(), target, stream);
  }

  // double heading = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_heading = this->_internal_heading();
  uint64_t raw_heading;
  memcpy(&raw_heading, &tmp_heading, sizeof(tmp_heading));
  if (raw_heading != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_heading(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.Obstacle)
  return target;
}

size_t Obstacle::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.Obstacle)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .pbt.Vec3 position = 3;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *position_);
  }

  // .pbt.Vec3 velocity = 4;
  if (this->_internal_has_velocity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *velocity_);
  }

  // .pbt.Vec3 size = 6;
  if (this->_internal_has_size()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *size_);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // .pbt.ObstacleType type = 2;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // double heading = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_heading = this->_internal_heading();
  uint64_t raw_heading;
  memcpy(&raw_heading, &tmp_heading, sizeof(tmp_heading));
  if (raw_heading != 0) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Obstacle::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Obstacle*>(
      &from));
}

void Obstacle::MergeFrom(const Obstacle& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.Obstacle)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _internal_mutable_position()->::pbt::Vec3::MergeFrom(from._internal_position());
  }
  if (from._internal_has_velocity()) {
    _internal_mutable_velocity()->::pbt::Vec3::MergeFrom(from._internal_velocity());
  }
  if (from._internal_has_size()) {
    _internal_mutable_size()->::pbt::Vec3::MergeFrom(from._internal_size());
  }
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (from._internal_type() != 0) {
    _internal_set_type(from._internal_type());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_heading = from._internal_heading();
  uint64_t raw_heading;
  memcpy(&raw_heading, &tmp_heading, sizeof(tmp_heading));
  if (raw_heading != 0) {
    _internal_set_heading(from._internal_heading());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Obstacle::CopyFrom(const Obstacle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.Obstacle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Obstacle::IsInitialized() const {
  return true;
}

void Obstacle::InternalSwap(Obstacle* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Obstacle, heading_)
      + sizeof(Obstacle::heading_)
      - PROTOBUF_FIELD_OFFSET(Obstacle, position_)>(
          reinterpret_cast<char*>(&position_),
          reinterpret_cast<char*>(&other->position_));
}

std::string Obstacle::GetTypeName() const {
  return "pbt.Obstacle";
}


// ===================================================================

class Cross::_Internal {
 public:
};

Cross::Cross(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  lane_lines_(arena),
  ground_signs_(arena),
  drivable_areas_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.Cross)
}
Cross::Cross(const Cross& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      lane_lines_(from.lane_lines_),
      ground_signs_(from.ground_signs_),
      drivable_areas_(from.drivable_areas_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pbt.Cross)
}

inline void Cross::SharedCtor() {
}

Cross::~Cross() {
  // @@protoc_insertion_point(destructor:pbt.Cross)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Cross::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Cross::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Cross::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.Cross)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  lane_lines_.Clear();
  ground_signs_.Clear();
  drivable_areas_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Cross::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .pbt.LaneLine lane_lines = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_lane_lines(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pbt.GroundSign ground_signs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ground_signs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .pbt.DrivableArea drivable_areas = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_drivable_areas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Cross::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.Cross)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pbt.LaneLine lane_lines = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_lane_lines_size()); i < n; i++) {
    const auto& repfield = this->_internal_lane_lines(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pbt.GroundSign ground_signs = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_ground_signs_size()); i < n; i++) {
    const auto& repfield = this->_internal_ground_signs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pbt.DrivableArea drivable_areas = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_drivable_areas_size()); i < n; i++) {
    const auto& repfield = this->_internal_drivable_areas(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.Cross)
  return target;
}

size_t Cross::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.Cross)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pbt.LaneLine lane_lines = 1;
  total_size += 1UL * this->_internal_lane_lines_size();
  for (const auto& msg : this->lane_lines_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .pbt.GroundSign ground_signs = 2;
  total_size += 1UL * this->_internal_ground_signs_size();
  for (const auto& msg : this->ground_signs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .pbt.DrivableArea drivable_areas = 3;
  total_size += 1UL * this->_internal_drivable_areas_size();
  for (const auto& msg : this->drivable_areas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Cross::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Cross*>(
      &from));
}

void Cross::MergeFrom(const Cross& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.Cross)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  lane_lines_.MergeFrom(from.lane_lines_);
  ground_signs_.MergeFrom(from.ground_signs_);
  drivable_areas_.MergeFrom(from.drivable_areas_);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Cross::CopyFrom(const Cross& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.Cross)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Cross::IsInitialized() const {
  return true;
}

void Cross::InternalSwap(Cross* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  lane_lines_.InternalSwap(&other->lane_lines_);
  ground_signs_.InternalSwap(&other->ground_signs_);
  drivable_areas_.InternalSwap(&other->drivable_areas_);
}

std::string Cross::GetTypeName() const {
  return "pbt.Cross";
}


// ===================================================================

class LaneLine::_Internal {
 public:
};

LaneLine::LaneLine(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  points_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.LaneLine)
}
LaneLine::LaneLine(const LaneLine& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      points_(from.points_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&color_) -
    reinterpret_cast<char*>(&id_)) + sizeof(color_));
  // @@protoc_insertion_point(copy_constructor:pbt.LaneLine)
}

inline void LaneLine::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&color_) -
    reinterpret_cast<char*>(&id_)) + sizeof(color_));
}

LaneLine::~LaneLine() {
  // @@protoc_insertion_point(destructor:pbt.LaneLine)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LaneLine::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void LaneLine::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void LaneLine::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.LaneLine)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  points_.Clear();
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&color_) -
      reinterpret_cast<char*>(&id_)) + sizeof(color_));
  _internal_metadata_.Clear<std::string>();
}

const char* LaneLine::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.LaneLineType type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::pbt::LaneLineType>(val));
        } else
          goto handle_unusual;
        continue;
      // .pbt.LaneLineColor color = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_color(static_cast<::pbt::LaneLineColor>(val));
        } else
          goto handle_unusual;
        continue;
      // repeated .pbt.Vec3 points = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_points(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // double confidence = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          confidence_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double width = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LaneLine::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.LaneLine)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // .pbt.LaneLineType type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  // .pbt.LaneLineColor color = 3;
  if (this->_internal_color() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_color(), target);
  }

  // repeated .pbt.Vec3 points = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_points_size()); i < n; i++) {
    const auto& repfield = this->_internal_points(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // double confidence = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_confidence = this->_internal_confidence();
  uint64_t raw_confidence;
  memcpy(&raw_confidence, &tmp_confidence, sizeof(tmp_confidence));
  if (raw_confidence != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_confidence(), target);
  }

  // double width = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_width = this->_internal_width();
  uint64_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_width(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.LaneLine)
  return target;
}

size_t LaneLine::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.LaneLine)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pbt.Vec3 points = 4;
  total_size += 1UL * this->_internal_points_size();
  for (const auto& msg : this->points_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // .pbt.LaneLineType type = 2;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // double confidence = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_confidence = this->_internal_confidence();
  uint64_t raw_confidence;
  memcpy(&raw_confidence, &tmp_confidence, sizeof(tmp_confidence));
  if (raw_confidence != 0) {
    total_size += 1 + 8;
  }

  // double width = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_width = this->_internal_width();
  uint64_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    total_size += 1 + 8;
  }

  // .pbt.LaneLineColor color = 3;
  if (this->_internal_color() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_color());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LaneLine::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const LaneLine*>(
      &from));
}

void LaneLine::MergeFrom(const LaneLine& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.LaneLine)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  points_.MergeFrom(from.points_);
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (from._internal_type() != 0) {
    _internal_set_type(from._internal_type());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_confidence = from._internal_confidence();
  uint64_t raw_confidence;
  memcpy(&raw_confidence, &tmp_confidence, sizeof(tmp_confidence));
  if (raw_confidence != 0) {
    _internal_set_confidence(from._internal_confidence());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_width = from._internal_width();
  uint64_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    _internal_set_width(from._internal_width());
  }
  if (from._internal_color() != 0) {
    _internal_set_color(from._internal_color());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void LaneLine::CopyFrom(const LaneLine& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.LaneLine)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LaneLine::IsInitialized() const {
  return true;
}

void LaneLine::InternalSwap(LaneLine* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  points_.InternalSwap(&other->points_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LaneLine, color_)
      + sizeof(LaneLine::color_)
      - PROTOBUF_FIELD_OFFSET(LaneLine, id_)>(
          reinterpret_cast<char*>(&id_),
          reinterpret_cast<char*>(&other->id_));
}

std::string LaneLine::GetTypeName() const {
  return "pbt.LaneLine";
}


// ===================================================================

class GroundSign::_Internal {
 public:
};

GroundSign::GroundSign(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  polygon_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.GroundSign)
}
GroundSign::GroundSign(const GroundSign& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      polygon_(from.polygon_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&id_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:pbt.GroundSign)
}

inline void GroundSign::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&id_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&id_)) + sizeof(type_));
}

GroundSign::~GroundSign() {
  // @@protoc_insertion_point(destructor:pbt.GroundSign)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GroundSign::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GroundSign::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GroundSign::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.GroundSign)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  polygon_.Clear();
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&id_)) + sizeof(type_));
  _internal_metadata_.Clear<std::string>();
}

const char* GroundSign::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.GroundSignType type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::pbt::GroundSignType>(val));
        } else
          goto handle_unusual;
        continue;
      // repeated .pbt.Vec3 polygon = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_polygon(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GroundSign::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.GroundSign)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // .pbt.GroundSignType type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  // repeated .pbt.Vec3 polygon = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_polygon_size()); i < n; i++) {
    const auto& repfield = this->_internal_polygon(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.GroundSign)
  return target;
}

size_t GroundSign::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.GroundSign)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pbt.Vec3 polygon = 3;
  total_size += 1UL * this->_internal_polygon_size();
  for (const auto& msg : this->polygon_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // .pbt.GroundSignType type = 2;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GroundSign::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const GroundSign*>(
      &from));
}

void GroundSign::MergeFrom(const GroundSign& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.GroundSign)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  polygon_.MergeFrom(from.polygon_);
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (from._internal_type() != 0) {
    _internal_set_type(from._internal_type());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void GroundSign::CopyFrom(const GroundSign& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.GroundSign)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroundSign::IsInitialized() const {
  return true;
}

void GroundSign::InternalSwap(GroundSign* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  polygon_.InternalSwap(&other->polygon_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GroundSign, type_)
      + sizeof(GroundSign::type_)
      - PROTOBUF_FIELD_OFFSET(GroundSign, id_)>(
          reinterpret_cast<char*>(&id_),
          reinterpret_cast<char*>(&other->id_));
}

std::string GroundSign::GetTypeName() const {
  return "pbt.GroundSign";
}


// ===================================================================

class DrivableArea::_Internal {
 public:
};

DrivableArea::DrivableArea(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  boundary_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.DrivableArea)
}
DrivableArea::DrivableArea(const DrivableArea& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      boundary_(from.boundary_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&confidence_, &from.confidence_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&confidence_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:pbt.DrivableArea)
}

inline void DrivableArea::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&confidence_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&confidence_)) + sizeof(id_));
}

DrivableArea::~DrivableArea() {
  // @@protoc_insertion_point(destructor:pbt.DrivableArea)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DrivableArea::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DrivableArea::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DrivableArea::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.DrivableArea)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  boundary_.Clear();
  ::memset(&confidence_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&confidence_)) + sizeof(id_));
  _internal_metadata_.Clear<std::string>();
}

const char* DrivableArea::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .pbt.Vec3 boundary = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_boundary(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // double confidence = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          confidence_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double speed_limit = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          speed_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DrivableArea::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.DrivableArea)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // repeated .pbt.Vec3 boundary = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_boundary_size()); i < n; i++) {
    const auto& repfield = this->_internal_boundary(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // double confidence = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_confidence = this->_internal_confidence();
  uint64_t raw_confidence;
  memcpy(&raw_confidence, &tmp_confidence, sizeof(tmp_confidence));
  if (raw_confidence != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_confidence(), target);
  }

  // double speed_limit = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_speed_limit = this->_internal_speed_limit();
  uint64_t raw_speed_limit;
  memcpy(&raw_speed_limit, &tmp_speed_limit, sizeof(tmp_speed_limit));
  if (raw_speed_limit != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_speed_limit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.DrivableArea)
  return target;
}

size_t DrivableArea::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.DrivableArea)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pbt.Vec3 boundary = 2;
  total_size += 1UL * this->_internal_boundary_size();
  for (const auto& msg : this->boundary_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // double confidence = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_confidence = this->_internal_confidence();
  uint64_t raw_confidence;
  memcpy(&raw_confidence, &tmp_confidence, sizeof(tmp_confidence));
  if (raw_confidence != 0) {
    total_size += 1 + 8;
  }

  // double speed_limit = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_speed_limit = this->_internal_speed_limit();
  uint64_t raw_speed_limit;
  memcpy(&raw_speed_limit, &tmp_speed_limit, sizeof(tmp_speed_limit));
  if (raw_speed_limit != 0) {
    total_size += 1 + 8;
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DrivableArea::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const DrivableArea*>(
      &from));
}

void DrivableArea::MergeFrom(const DrivableArea& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.DrivableArea)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  boundary_.MergeFrom(from.boundary_);
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_confidence = from._internal_confidence();
  uint64_t raw_confidence;
  memcpy(&raw_confidence, &tmp_confidence, sizeof(tmp_confidence));
  if (raw_confidence != 0) {
    _internal_set_confidence(from._internal_confidence());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_speed_limit = from._internal_speed_limit();
  uint64_t raw_speed_limit;
  memcpy(&raw_speed_limit, &tmp_speed_limit, sizeof(tmp_speed_limit));
  if (raw_speed_limit != 0) {
    _internal_set_speed_limit(from._internal_speed_limit());
  }
  if (from._internal_id() != 0) {
    _internal_set_id(from._internal_id());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void DrivableArea::CopyFrom(const DrivableArea& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.DrivableArea)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DrivableArea::IsInitialized() const {
  return true;
}

void DrivableArea::InternalSwap(DrivableArea* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  boundary_.InternalSwap(&other->boundary_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DrivableArea, id_)
      + sizeof(DrivableArea::id_)
      - PROTOBUF_FIELD_OFFSET(DrivableArea, confidence_)>(
          reinterpret_cast<char*>(&confidence_),
          reinterpret_cast<char*>(&other->confidence_));
}

std::string DrivableArea::GetTypeName() const {
  return "pbt.DrivableArea";
}


// ===================================================================

class DrivingDataFrame::_Internal {
 public:
  static const ::pbt::Ego& ego(const DrivingDataFrame* msg);
  static const ::pbt::Cross& cross(const DrivingDataFrame* msg);
};

const ::pbt::Ego&
DrivingDataFrame::_Internal::ego(const DrivingDataFrame* msg) {
  return *msg->ego_;
}
const ::pbt::Cross&
DrivingDataFrame::_Internal::cross(const DrivingDataFrame* msg) {
  return *msg->cross_;
}
DrivingDataFrame::DrivingDataFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:pbt.DrivingDataFrame)
}
DrivingDataFrame::DrivingDataFrame(const DrivingDataFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_ego()) {
    ego_ = new ::pbt::Ego(*from.ego_);
  } else {
    ego_ = nullptr;
  }
  if (from._internal_has_cross()) {
    cross_ = new ::pbt::Cross(*from.cross_);
  } else {
    cross_ = nullptr;
  }
  ::memcpy(&frame_id_, &from.frame_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&frame_id_)) + sizeof(timestamp_));
  // @@protoc_insertion_point(copy_constructor:pbt.DrivingDataFrame)
}

inline void DrivingDataFrame::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&ego_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&ego_)) + sizeof(timestamp_));
}

DrivingDataFrame::~DrivingDataFrame() {
  // @@protoc_insertion_point(destructor:pbt.DrivingDataFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DrivingDataFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete ego_;
  if (this != internal_default_instance()) delete cross_;
}

void DrivingDataFrame::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DrivingDataFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:pbt.DrivingDataFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && ego_ != nullptr) {
    delete ego_;
  }
  ego_ = nullptr;
  if (GetArenaForAllocation() == nullptr && cross_ != nullptr) {
    delete cross_;
  }
  cross_ = nullptr;
  ::memset(&frame_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&frame_id_)) + sizeof(timestamp_));
  _internal_metadata_.Clear<std::string>();
}

const char* DrivingDataFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 frame_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          frame_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.Ego ego = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_ego(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .pbt.Cross cross = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_cross(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DrivingDataFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbt.DrivingDataFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 frame_id = 1;
  if (this->_internal_frame_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_frame_id(), target);
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_timestamp(), target);
  }

  // .pbt.Ego ego = 3;
  if (this->_internal_has_ego()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::ego(this),
        _Internal::ego(this).GetCachedSize(), target, stream);
  }

  // .pbt.Cross cross = 4;
  if (this->_internal_has_cross()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::cross(this),
        _Internal::cross(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbt.DrivingDataFrame)
  return target;
}

size_t DrivingDataFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbt.DrivingDataFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .pbt.Ego ego = 3;
  if (this->_internal_has_ego()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *ego_);
  }

  // .pbt.Cross cross = 4;
  if (this->_internal_has_cross()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *cross_);
  }

  // int64 frame_id = 1;
  if (this->_internal_frame_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_frame_id());
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DrivingDataFrame::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const DrivingDataFrame*>(
      &from));
}

void DrivingDataFrame::MergeFrom(const DrivingDataFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbt.DrivingDataFrame)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_ego()) {
    _internal_mutable_ego()->::pbt::Ego::MergeFrom(from._internal_ego());
  }
  if (from._internal_has_cross()) {
    _internal_mutable_cross()->::pbt::Cross::MergeFrom(from._internal_cross());
  }
  if (from._internal_frame_id() != 0) {
    _internal_set_frame_id(from._internal_frame_id());
  }
  if (from._internal_timestamp() != 0) {
    _internal_set_timestamp(from._internal_timestamp());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void DrivingDataFrame::CopyFrom(const DrivingDataFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbt.DrivingDataFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DrivingDataFrame::IsInitialized() const {
  return true;
}

void DrivingDataFrame::InternalSwap(DrivingDataFrame* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DrivingDataFrame, timestamp_)
      + sizeof(DrivingDataFrame::timestamp_)
      - PROTOBUF_FIELD_OFFSET(DrivingDataFrame, ego_)>(
          reinterpret_cast<char*>(&ego_),
          reinterpret_cast<char*>(&other->ego_));
}

std::string DrivingDataFrame::GetTypeName() const {
  return "pbt.DrivingDataFrame";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pbt
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pbt::Vec3*
Arena::CreateMaybeMessage< ::pbt::Vec3 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::Vec3 >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::Ego*
Arena::CreateMaybeMessage< ::pbt::Ego >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::Ego >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::EgoVehicle*
Arena::CreateMaybeMessage< ::pbt::EgoVehicle >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::EgoVehicle >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::Obstacle*
Arena::CreateMaybeMessage< ::pbt::Obstacle >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::Obstacle >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::Cross*
Arena::CreateMaybeMessage< ::pbt::Cross >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::Cross >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::LaneLine*
Arena::CreateMaybeMessage< ::pbt::LaneLine >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::LaneLine >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::GroundSign*
Arena::CreateMaybeMessage< ::pbt::GroundSign >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::GroundSign >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::DrivableArea*
Arena::CreateMaybeMessage< ::pbt::DrivableArea >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::DrivableArea >(arena);
}
template<> PROTOBUF_NOINLINE ::pbt::DrivingDataFrame*
Arena::CreateMaybeMessage< ::pbt::DrivingDataFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pbt::DrivingDataFrame >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
